# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/article/:title

# Setup
title:            Patrick Blog
tagline:          'blog'
description:      'Patrick Blog'
url:              http://atomic111.github.io
baseurl:
commentsystem:    google
disqus:           example

author:
  name:           Patrick Münch
  url:            https://twitter.com/atomiczero111

paginate:         5

# Custom vars
icon:             /assets/images/logo.jpeg
cover:            /assets/images/cover.jpeg

social:
  - icon:         twitter
    url:          https://twitter.com/atomiczero111
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/atomic111
    desc:         Fork me on github

menu:

  - title:        Home
    url:          /

copyright:
  author:         Patrick Münch
  url:            http://atomic111.github.io
  type_title:     All rights reserved
#  type_title:     Some rights reserved
#  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-74418092-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
